"""
PDF & Excel export — Feature 17.
Exports marketing_data as downloadable .xlsx or .pdf files.
"""
import io
import logging
from datetime import datetime, timedelta, timezone
from typing import Optional

from fastapi import APIRouter, Depends, Query
from fastapi.responses import StreamingResponse
from motor.motor_asyncio import AsyncIOMotorDatabase

from app.database import get_db
from app.middleware.auth import get_current_user
from app.routers.whitelabel import get_branding

logger = logging.getLogger(__name__)

router = APIRouter(prefix="/api/v1/export", tags=["export"])


# ── Shared helpers ────────────────────────────────────────────────────────────

async def _fetch_rows(
    db: AsyncIOMotorDatabase,
    user_id: str,
    platform: Optional[str],
    connector_id: Optional[str],
    campaign_id: Optional[str],
    date_from: str,
    date_to: str,
) -> list[dict]:
    match: dict = {
        "user_id": user_id,
        "date": {"$gte": date_from, "$lte": date_to},
    }
    if platform:
        match["platform"] = platform
    if connector_id:
        match["connector_id"] = connector_id
    if campaign_id:
        match["campaign_id"] = campaign_id

    cursor = db["marketing_data"].find(match, {"_id": 0}).sort("date", 1).limit(5000)
    return [doc async for doc in cursor]


def _default_date_range() -> tuple[str, str]:
    today = datetime.now(timezone.utc)
    return (today - timedelta(days=30)).strftime("%Y-%m-%d"), today.strftime("%Y-%m-%d")


METRIC_COLS = ["impressions", "clicks", "spend", "ctr", "cpa", "roas", "cpm", "reach", "conversions"]


# ── Excel export ──────────────────────────────────────────────────────────────

def _build_excel(rows: list[dict], date_from: str, date_to: str, branding: dict | None = None) -> bytes:
    from openpyxl import Workbook
    from openpyxl.styles import Font, PatternFill, Alignment, Border, Side
    from openpyxl.utils import get_column_letter

    b = branding or {}
    company   = b.get("company_name", "mediaERP")
    pri_color = (b.get("primary_color") or "#18181b").lstrip("#").upper()
    footer    = b.get("footer_text") or f"Generated by {company}"

    wb = Workbook()
    ws = wb.active
    ws.title = "Campaign Data"

    # Header style
    hdr_font   = Font(bold=True, color="FFFFFF", size=11)
    hdr_fill   = PatternFill("solid", start_color=pri_color if len(pri_color) == 6 else "18181B")
    hdr_align  = Alignment(horizontal="center", vertical="center", wrap_text=True)
    thin_side  = Side(style="thin", color="E5E7EB")
    thin_border = Border(bottom=thin_side)

    headers = ["Date", "Platform", "Campaign ID", "Campaign Name"] + [m.upper() for m in METRIC_COLS]

    # Title row
    ws.merge_cells("A1:P1")
    title_cell = ws["A1"]
    title_cell.value = f"{company} — Campaign Performance: {date_from} to {date_to}"
    title_cell.font = Font(bold=True, size=13, color="18181B")
    title_cell.alignment = Alignment(horizontal="left", vertical="center")
    title_cell.fill = PatternFill("solid", start_color="F9FAFB")
    ws.row_dimensions[1].height = 28

    # Header row
    for col_idx, h in enumerate(headers, start=1):
        cell = ws.cell(row=2, column=col_idx, value=h)
        cell.font = hdr_font
        cell.fill = hdr_fill
        cell.alignment = hdr_align
        cell.border = thin_border
    ws.row_dimensions[2].height = 22

    # Data rows
    for row_idx, row in enumerate(rows, start=3):
        m = row.get("metrics", {})
        values = [
            row.get("date", ""),
            row.get("platform", ""),
            row.get("campaign_id", ""),
            row.get("campaign_name", ""),
        ] + [m.get(metric) for metric in METRIC_COLS]

        for col_idx, val in enumerate(values, start=1):
            cell = ws.cell(row=row_idx, column=col_idx, value=val)
            cell.alignment = Alignment(horizontal="left", vertical="center")
            if row_idx % 2 == 0:
                cell.fill = PatternFill("solid", start_color="F9FAFB")

        # Number formats for metric columns
        metric_start = 5  # column index where metrics begin
        fmt_map = {
            0: '#,##0',        # impressions
            1: '#,##0',        # clicks
            2: '$#,##0.00',   # spend
            3: '0.00"%"',     # ctr
            4: '$#,##0.00',   # cpa
            5: '0.00',         # roas
            6: '$#,##0.00',   # cpm
            7: '#,##0',        # reach
            8: '#,##0',        # conversions
        }
        for i, metric in enumerate(METRIC_COLS):
            cell = ws.cell(row=row_idx, column=metric_start + i)
            if fmt_map.get(i):
                cell.number_format = fmt_map[i]

    # Column widths
    col_widths = [12, 16, 24, 36] + [14] * len(METRIC_COLS)
    for i, width in enumerate(col_widths, start=1):
        ws.column_dimensions[get_column_letter(i)].width = width

    # Freeze panes below headers
    ws.freeze_panes = "A3"

    buf = io.BytesIO()
    wb.save(buf)
    return buf.getvalue()


@router.get("/campaigns/excel", summary="Export campaign data as Excel (.xlsx)")
async def export_excel(
    platform: Optional[str] = Query(None),
    connector_id: Optional[str] = Query(None),
    campaign_id: Optional[str] = Query(None),
    date_from: Optional[str] = Query(None),
    date_to: Optional[str] = Query(None),
    db: AsyncIOMotorDatabase = Depends(get_db),
    current_user: dict = Depends(get_current_user),
):
    user_id = str(current_user["_id"])
    df, dt = _default_date_range()
    date_from = date_from or df
    date_to   = date_to   or dt

    rows = await _fetch_rows(db, user_id, platform, connector_id, campaign_id, date_from, date_to)
    branding = await get_branding(db, user_id)
    xlsx_bytes = _build_excel(rows, date_from, date_to, branding)

    company = (branding.get("company_name") or "mediaerp").lower().replace(" ", "_")
    filename = f"{company}_campaigns_{date_from}_{date_to}.xlsx"
    return StreamingResponse(
        io.BytesIO(xlsx_bytes),
        media_type="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
        headers={"Content-Disposition": f'attachment; filename="{filename}"'},
    )


# ── PDF export ────────────────────────────────────────────────────────────────

def _build_pdf(rows: list[dict], date_from: str, date_to: str, branding: dict | None = None) -> bytes:
    from reportlab.lib import colors
    from reportlab.lib.pagesizes import A4, landscape
    from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
    from reportlab.lib.units import mm
    from reportlab.platypus import SimpleDocTemplate, Table, TableStyle, Paragraph, Spacer
    from reportlab.lib.enums import TA_LEFT, TA_CENTER

    b = branding or {}
    company   = b.get("company_name", "mediaERP")
    pri_hex   = b.get("primary_color") or "#18181b"
    footer_txt = b.get("footer_text") or f"Generated by {company}"
    pri_color = colors.HexColor(pri_hex)

    buf = io.BytesIO()
    doc = SimpleDocTemplate(
        buf,
        pagesize=landscape(A4),
        leftMargin=15 * mm,
        rightMargin=15 * mm,
        topMargin=15 * mm,
        bottomMargin=15 * mm,
    )

    styles = getSampleStyleSheet()
    title_style = ParagraphStyle(
        "Title",
        parent=styles["Normal"],
        fontSize=16,
        fontName="Helvetica-Bold",
        textColor=colors.HexColor("#18181B"),
        spaceAfter=4,
    )
    subtitle_style = ParagraphStyle(
        "Subtitle",
        parent=styles["Normal"],
        fontSize=10,
        fontName="Helvetica",
        textColor=colors.HexColor("#6B7280"),
        spaceAfter=12,
    )
    cell_style = ParagraphStyle(
        "Cell",
        parent=styles["Normal"],
        fontSize=8,
        fontName="Helvetica",
        wordWrap="CJK",
    )

    story = [
        Paragraph(f"{company} — Campaign Performance Report", title_style),
        Paragraph(
            f"Period: {date_from} to {date_to}  |  Generated: {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')}  |  Rows: {len(rows)}",
            subtitle_style,
        ),
        Spacer(1, 4),
    ]

    # Table headers
    display_metrics = ["impressions", "clicks", "spend", "ctr", "roas"]
    col_headers = ["Date", "Platform", "Campaign", "Imp.", "Clicks", "Spend ($)", "CTR (%)", "ROAS"]

    def _fmt_val(v, metric):
        if v is None:
            return "-"
        if metric == "spend":
            return f"${float(v):,.2f}"
        if metric == "ctr":
            return f"{float(v):.2f}%"
        if metric == "roas":
            return f"{float(v):.2f}"
        return f"{int(v):,}" if isinstance(v, (int, float)) else str(v)

    data = [col_headers]
    for row in rows:
        m = row.get("metrics", {})
        campaign_name = row.get("campaign_name", "")[:40]
        data.append([
            row.get("date", ""),
            row.get("platform", ""),
            campaign_name,
        ] + [_fmt_val(m.get(metric), metric) for metric in display_metrics])

    # Column widths (landscape A4 = 277mm usable)
    col_widths = [22*mm, 28*mm, 80*mm, 22*mm, 22*mm, 30*mm, 22*mm, 22*mm]

    # Truncate to 500 rows for PDF
    if len(data) > 501:
        data = data[:501]
        data.append(["..." for _ in col_headers])

    table = Table(data, colWidths=col_widths, repeatRows=1)
    table.setStyle(TableStyle([
        # Header
        ("BACKGROUND",  (0, 0), (-1, 0), pri_color),
        ("TEXTCOLOR",   (0, 0), (-1, 0), colors.white),
        ("FONTNAME",    (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTSIZE",    (0, 0), (-1, 0), 8),
        ("ALIGN",       (0, 0), (-1, 0), "CENTER"),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#F9FAFB")]),
        ("FONTNAME",    (0, 1), (-1, -1), "Helvetica"),
        ("FONTSIZE",    (0, 1), (-1, -1), 7.5),
        ("ALIGN",       (3, 1), (-1, -1), "RIGHT"),
        ("GRID",        (0, 0), (-1, -1), 0.4, colors.HexColor("#E5E7EB")),
        ("TOPPADDING",  (0, 0), (-1, -1), 5),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
        ("LEFTPADDING", (0, 0), (-1, -1), 6),
        ("RIGHTPADDING", (0, 0), (-1, -1), 6),
    ]))

    story.append(table)
    doc.build(story)
    return buf.getvalue()


@router.get("/campaigns/pdf", summary="Export campaign data as PDF")
async def export_pdf(
    platform: Optional[str] = Query(None),
    connector_id: Optional[str] = Query(None),
    campaign_id: Optional[str] = Query(None),
    date_from: Optional[str] = Query(None),
    date_to: Optional[str] = Query(None),
    db: AsyncIOMotorDatabase = Depends(get_db),
    current_user: dict = Depends(get_current_user),
):
    user_id = str(current_user["_id"])
    df, dt = _default_date_range()
    date_from = date_from or df
    date_to   = date_to   or dt

    rows = await _fetch_rows(db, user_id, platform, connector_id, campaign_id, date_from, date_to)
    branding = await get_branding(db, user_id)
    pdf_bytes = _build_pdf(rows, date_from, date_to, branding)

    company = (branding.get("company_name") or "mediaerp").lower().replace(" ", "_")
    filename = f"{company}_campaigns_{date_from}_{date_to}.pdf"
    return StreamingResponse(
        io.BytesIO(pdf_bytes),
        media_type="application/pdf",
        headers={"Content-Disposition": f'attachment; filename="{filename}"'},
    )
